services:
  - type: web
    name: graphsentinel-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://<username>:<password>@cluster.mongodb.net/frauddb
      - key: KAFKA_BROKERS
        value: localhost:9092
      - key: KAFKA_USERNAME
        value: ""
      - key: KAFKA_PASSWORD
        value: ""

  - type: web
    name: graphsentinel-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: graphsentinel-backend
          property: host
        # Render doesn't natively prepend https for fromService host, so we might need to manually set it in dashboard, 
        # but this sets a dependency so Backend starts before Frontend.
      - key: NEXT_PUBLIC_SOCKET_URL
        fromService:
          type: web
          name: graphsentinel-backend
          property: host
